'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('fs'); const os = require('os'); const path = require('path');
const { createStravaChallenge } = require('../lib/strava-challenge');
function temp() { return fs.mkdtempSync(path.join(os.tmpdir(), 'strava-service-')); }
function response(body, status = 200) { return { ok: status < 300, status, headers: { get: () => null }, text: async () => JSON.stringify(body) }; }
function fixture({ now = new Date('2026-03-23T12:00:00Z'), activities = [], sameAthlete = false, envOverrides = {} } = {}) { let clock = new Date(now), athlete = 41; const calls = []; const env = { STRAVA_CHALLENGE_CRYPTO_SECRET: 'x'.repeat(48), STRAVA_CLIENT_ID: 'id', STRAVA_CLIENT_SECRET: 'secret', STRAVA_REDIRECT_URI: 'https://example.test/callback', CHALLENGE_BASE_URL: 'https://example.test', STRAVA_CHALLENGE_YEAR: '2026', STRAVA_CHALLENGE_START_DATE: '2026-01-01', STRAVA_CHALLENGE_YANNICK_EMAIL: 'yannick@example.test', STRAVA_CHALLENGE_EMMA_EMAIL: 'emma@example.test', ...envOverrides }; const api = createStravaChallenge({ dataDir: temp(), now: () => new Date(clock), env, sendEmail: async (...args) => { calls.push(args); return { id: 'mail' }; }, fetchImpl: async (url, options) => { if (url.includes('/oauth/token')) return response({ access_token: 'access', refresh_token: 'refresh-new', expires_at: Math.floor(clock.getTime() / 1000) + 7200, athlete: { id: sameAthlete ? 42 : ++athlete, firstname: 'Test' } }); if (url.includes('/athlete/activities')) return response(activities); throw new Error(`unexpected ${url} ${options && options.method}`); }, logger: { warn() {} } }); return { api, calls, setClock: d => { clock = new Date(d); } }; }
test('invite is hashed, participant-bound, and OAuth state is single use', async () => { const { api } = fixture(); const invite = await api.generateInvite('yannick'); const status = await api.getAdminStatus(); assert.equal(JSON.stringify(status).includes(invite.token), false); const prepared = await api.prepareOAuth(invite.token); assert.equal(prepared.participantId, 'yannick'); assert.equal(prepared.authorizationUrl, prepared.authorizeUrl); const state = new URL(prepared.authorizationUrl).searchParams.get('state'); const done = await api.completeOAuth({ code: 'code', state, scope: 'activity:read_all' }); assert.equal(done.participantId, 'yannick'); await assert.rejects(() => api.completeOAuth({ code: 'code', state, scope: 'activity:read_all' })); });
test('zero invitation TTL keeps an unused connection invitation valid', async () => { const { api } = fixture(); await api.updateConfig({ inviteTtlHours: 0 }); const invite = await api.generateInvite('yannick'); assert.equal(invite.expiresAt, null); const prepared = await api.prepareOAuth(invite.token); assert.equal(prepared.participantId, 'yannick'); });
test('OAuth preparation fails before issuing state when credential encryption is unconfigured', async () => { for (const secret of [undefined, 'too-short']) { const { api } = fixture({ envOverrides: { STRAVA_CHALLENGE_CRYPTO_SECRET: secret } }); const invite = await api.generateInvite('yannick'); await assert.rejects(() => api.prepareOAuth(invite.token), /STRAVA_CHALLENGE_CRYPTO_SECRET/); assert.equal(api._test.store.read(s => Object.keys(s.oauthStates).length), 0); } });
test('missing scope and cross athlete connection are rejected', async () => { const { api } = fixture({ sameAthlete: true }); const one = await api.generateInvite('yannick'); const st = new URL((await api.prepareOAuth(one.token)).authorizeUrl).searchParams.get('state'); await assert.rejects(() => api.completeOAuth({ code: 'x', state: st, scope: 'read' })); const two = await api.generateInvite('emma'); const st2 = new URL((await api.prepareOAuth(two.token)).authorizeUrl).searchParams.get('state'); await api.completeOAuth({ code: 'x', state: st2, scope: 'activity:read_all' }); const three = await api.generateInvite('yannick'); const st3 = new URL((await api.prepareOAuth(three.token)).authorizeUrl).searchParams.get('state'); await assert.rejects(() => api.completeOAuth({ code: 'x', state: st3, scope: 'activity:read_all' }), /already connected/); });
test('finalization snapshots once and duplicate result mail is prevented', async () => { const activities = [{ id: 1, name: 'Run', sport_type: 'Run', start_date: '2026-03-17T12:00:00Z', distance: 5000, moving_time: 1800, elapsed_time: 1800 }]; const { api, calls } = fixture({ activities }); for (const id of ['yannick', 'emma']) { const invite = await api.generateInvite(id); const state = new URL((await api.prepareOAuth(invite.token)).authorizeUrl).searchParams.get('state'); await api.completeOAuth({ code: 'x', state, scope: 'activity:read_all' }); } const first = await api.finalizeWeek({ weekStart: '2026-03-16' }); const second = await api.finalizeWeek({ weekStart: '2026-03-16' }); assert.equal(first.winner, 'emma'); assert.equal(second.alreadyFinalized, true); assert.equal(calls.length, 2); const publicWeek = await api.getPublicWeek('2026-03-16'); assert.equal(publicWeek.activities.length, 1); });
