'use strict';
const { getWeekBounds, getChallengeRange, formatWeekDateRange, CHALLENGE_TIME_ZONE } = require('./time');

const PARTICIPANTS = Object.freeze({ yannick: Object.freeze({ id: 'yannick', name: 'Yannick', color: 'red' }), emma: Object.freeze({ id: 'emma', name: 'Emma', color: 'blue' }) });
const THRESHOLDS = Object.freeze({ RUN_MIN_DISTANCE_METERS: 4000, SWIM_MIN_DISTANCE_METERS: 3000, WALK_MIN_DISTANCE_METERS: 2000, GYM_MIN_SECONDS: 1200, PADDLE_MIN_SECONDS: 1800, CLIMB_MIN_SECONDS: 3600 });
const ENUMS = Object.freeze({ run: new Set(['Run', 'TrailRun', 'VirtualRun']), swim: new Set(['Swim']), walk: new Set(['Walk']), gym: new Set(['Workout', 'WeightTraining', 'Crossfit', 'HighIntensityIntervalTraining']), paddle: new Set(['Canoeing', 'Kayaking', 'Rowing', 'VirtualRow', 'StandUpPaddling']), climb: new Set(['RockClimbing']) });
function categorizeSportType(activity = {}) { const v = activity.sport_type || activity.sportType || activity.type || ''; for (const [category, values] of Object.entries(ENUMS)) if (values.has(v)) return category; return 'other'; }
function number(v) { return Number.isFinite(Number(v)) ? Number(v) : 0; }
function activityDurationSeconds(a = {}, category = categorizeSportType(a)) { const moving = number(a.moving_time ?? a.movingTime), elapsed = number(a.elapsed_time ?? a.elapsedTime); return ['gym', 'climb'].includes(category) ? (elapsed || moving) : (moving || elapsed); }
function prettyAmount(value, type) { if (type === 'distance') return `${(value / 1000).toFixed(2)} km`; const h = Math.floor(value / 3600), m = Math.floor((value % 3600) / 60), s = Math.floor(value % 60); return h ? `${h}h ${m}m` : m ? `${m}m ${s}s` : `${s}s`; }
function evaluateActivity(activity = {}) {
  const category = categorizeSportType(activity); const distance = number(activity.distance); const durationField = ['gym', 'climb'].includes(category) ? (number(activity.elapsed_time ?? activity.elapsedTime) ? 'elapsed_time' : 'moving_time') : (number(activity.moving_time ?? activity.movingTime) ? 'moving_time' : 'elapsed_time');
  const challengeDurationSeconds = activityDurationSeconds(activity, category);
  const specs = { run: ['distance', THRESHOLDS.RUN_MIN_DISTANCE_METERS], swim: ['distance', THRESHOLDS.SWIM_MIN_DISTANCE_METERS], walk: ['distance', THRESHOLDS.WALK_MIN_DISTANCE_METERS], gym: ['duration', THRESHOLDS.GYM_MIN_SECONDS], paddle: ['duration', THRESHOLDS.PADDLE_MIN_SECONDS], climb: ['duration', THRESHOLDS.CLIMB_MIN_SECONDS] };
  if (!specs[category]) return { category, qualifies: false, thresholdType: null, actual: 0, required: null, difference: null, durationField, challengeDurationSeconds, explanation: 'Unsupported Strava activity type' };
  const [thresholdType, required] = specs[category]; const actual = thresholdType === 'distance' ? distance : challengeDurationSeconds; const difference = actual - required; const qualifies = difference >= 0;
  const noun = thresholdType === 'distance' ? 'distance' : 'time';
  return { category, qualifies, thresholdType, actual, required, difference, durationField, challengeDurationSeconds, explanation: qualifies ? `Qualified — ${prettyAmount(actual, thresholdType)} (${prettyAmount(difference, thresholdType)} over ${noun} minimum)` : `${prettyAmount(-difference, thresholdType)} short of ${prettyAmount(required, thresholdType)}` };
}
function normalizeActivity(raw = {}, participantId, syncedAt = new Date()) { const evaluation = evaluateActivity(raw); return { id: String(raw.id || raw.activity_id || ''), externalId: String(raw.id || raw.activity_id || ''), participantId, name: String(raw.name || 'Untitled activity'), sportType: raw.sport_type || raw.sportType || raw.type || 'Unknown', type: raw.type || raw.sport_type || 'Unknown', startDate: raw.start_date || raw.startDate || null, startDateLocal: raw.start_date_local || raw.startDateLocal || null, distance: number(raw.distance), movingTime: number(raw.moving_time ?? raw.movingTime), elapsedTime: number(raw.elapsed_time ?? raw.elapsedTime), syncedAt: new Date(syncedAt).toISOString(), ...evaluation }; }
function withCurrentEvaluation(activity = {}) { return { ...activity, ...evaluateActivity(activity) }; }
function inBounds(a, bounds) { const start = new Date(a.startDate || a.start_date).getTime(); return Number.isFinite(start) && start >= bounds.start.getTime() && start < bounds.end.getTime(); }
function participantActivities(activities, id, bounds) { return activities.filter(a => !a.deletedAt && a.participantId === id && (!bounds || inBounds(a, bounds))); }
function calculateParticipantStats(activities, participantId, bounds) { const list = participantActivities(activities, participantId, bounds).map(withCurrentEvaluation); const qualified = list.filter(a => a.qualifies); const stat = { qualifyingActivities: qualified.length, totalActivities: list.length, qualifyingActivityTime: qualified.reduce((n, a) => n + number(a.challengeDurationSeconds), 0), totalActivityTime: list.reduce((n, a) => n + activityDurationSeconds(a), 0), runningDistance: 0, swimmingDistance: 0, walkingDistance: 0, paddlingRowingTime: 0, paddlingRowingDistance: 0, gymTime: 0, climbingTime: 0, totalDistance: list.reduce((n, a) => n + number(a.distance), 0) };
  for (const a of list) { if (a.category === 'run') stat.runningDistance += number(a.distance); if (a.category === 'swim') stat.swimmingDistance += number(a.distance); if (a.category === 'walk') stat.walkingDistance += number(a.distance); if (a.category === 'paddle') { stat.paddlingRowingTime += activityDurationSeconds(a); stat.paddlingRowingDistance += number(a.distance); } if (a.category === 'gym') stat.gymTime += activityDurationSeconds(a); if (a.category === 'climb') stat.climbingTime += activityDurationSeconds(a); } return stat; }
function calculateWeekResult(activities, bounds) { const yannick = calculateParticipantStats(activities, 'yannick', bounds), emma = calculateParticipantStats(activities, 'emma', bounds); let winner = null, winningMethod = 'true_tie'; if (yannick.qualifyingActivities !== emma.qualifyingActivities) { winner = yannick.qualifyingActivities > emma.qualifyingActivities ? 'yannick' : 'emma'; winningMethod = 'activity_count'; } else if (yannick.qualifyingActivityTime !== emma.qualifyingActivityTime) { winner = yannick.qualifyingActivityTime > emma.qualifyingActivityTime ? 'yannick' : 'emma'; winningMethod = 'activity_time_tiebreaker'; } return { weekStart: bounds.weekStart, dateRange: formatWeekDateRange(bounds), bounds: { start: bounds.start.toISOString(), end: bounds.end.toISOString() }, yannick, emma, winner, winningMethod, pointAwarded: Boolean(winner), finalized: false }; }
function calculateSeason(finalizedWeeks = [], activities = [], config = {}) { const range = getChallengeRange(config); const weeks = finalizedWeeks.filter(w => new Date(w.bounds?.start || `${w.weekStart}T00:00:00Z`) >= range.start && new Date(w.bounds?.start || `${w.weekStart}T00:00:00Z`) < range.end).sort((a,b) => String(a.weekStart).localeCompare(String(b.weekStart))); const points = { yannick: 0, emma: 0 }, wins = { yannick: 0, emma: 0 }, ties = weeks.filter(w => !w.winner).length, tiebreakerWins = { yannick: 0, emma: 0 };
  for (const w of weeks) if (w.winner) { points[w.winner]++; wins[w.winner]++; if (w.winningMethod === 'activity_time_tiebreaker') tiebreakerWins[w.winner]++; }
  const stats = { yannick: calculateParticipantStats(activities, 'yannick'), emma: calculateParticipantStats(activities, 'emma') };
  for (const id of Object.keys(stats)) { const own = participantActivities(activities, id).filter(a => { const t = new Date(a.startDate).getTime(); return t >= range.start && t < range.end; }); stats[id] = calculateParticipantStats(own, id); stats[id].challengePoints = points[id]; stats[id].weeklyWins = wins[id]; stats[id].trueTies = ties; stats[id].tiebreakerWins = tiebreakerWins[id]; }
  const run = (id, reversed = false) => { let current = 0, longest = 0; const list = reversed ? [...weeks].reverse() : weeks; for (const w of list) { if (w.winner === id) { current++; longest = Math.max(longest, current); } else current = 0; } return { current, longest }; };
  const streaks = { yannick: run('yannick'), emma: run('emma') };
  const closestWeek = weeks.reduce((best, w) => { const gap = Math.abs((w.yannick?.qualifyingActivities || 0) - (w.emma?.qualifyingActivities || 0)); return !best || gap < best.gap ? { weekStart: w.weekStart, gap } : best; }, null);
  const biggestVictory = weeks.reduce((best, w) => { const gap = Math.abs((w.yannick?.qualifyingActivities || 0) - (w.emma?.qualifyingActivities || 0)); return !w.winner || !best || gap > best.gap ? (!w.winner ? best : { weekStart: w.weekStart, winner: w.winner, gap }) : best; }, null);
  const mostActiveWeek = weeks.reduce((best, w) => { const total = (w.yannick?.totalActivities || 0) + (w.emma?.totalActivities || 0); return !best || total > best.total ? { weekStart: w.weekStart, total } : best; }, null);
  return { year: range.year, points, wins, trueTies: ties, tiebreakerWins, participants: stats, finalizedWeeks: weeks.length, headToHead: { yannick: wins.yannick, emma: wins.emma, ties }, fun: { streaks, closestWeek, biggestVictory, mostActiveWeek } }; }
function publicActivity(a) { const { participantId, name, sportType, type, startDate, startDateLocal, distance, movingTime, elapsedTime, category, qualifies, thresholdType, actual, required, difference, durationField, challengeDurationSeconds, explanation, externalId, id } = a; return { id: externalId || id, participantId, athlete: PARTICIPANTS[participantId], name, sportType: sportType || type, startDate, startDateLocal, distance, distanceMeters: distance, movingTime, elapsedTime, durationSeconds: challengeDurationSeconds, category, qualifies, thresholdType, actual, required, difference, durationField, challengeDurationSeconds, explanation }; }
function publicStats(s = {}) { const keys = ['qualifyingActivities', 'totalActivities', 'qualifyingActivityTime', 'totalActivityTime', 'runningDistance', 'swimmingDistance', 'walkingDistance', 'paddlingRowingTime', 'paddlingRowingDistance', 'gymTime', 'climbingTime', 'totalDistance', 'challengePoints', 'weeklyWins', 'trueTies', 'tiebreakerWins']; return Object.fromEntries(keys.filter(k => s[k] !== undefined).map(k => [k, s[k]])); }
function buildPublicDashboard(state = {}, now = new Date()) { const activities = Object.values(state.activities || {}).filter(a => !a.deletedAt); const config = state.config || {}; const weeks = state.weeks || state.finalizedWeeks || {}; const bounds = getWeekBounds(now); const result = calculateWeekResult(activities, bounds); const currentWeek = { ...result, dateLabel: result.dateRange, score: { yannick: result.yannick.qualifyingActivities, emma: result.emma.qualifyingActivities }, qualifyingTimeSeconds: { yannick: result.yannick.qualifyingActivityTime, emma: result.emma.qualifyingActivityTime }, stats: { yannick: publicStats(result.yannick), emma: publicStats(result.emma) }, yannick: publicStats(result.yannick), emma: publicStats(result.emma) }; const rawSeason = calculateSeason(Object.values(weeks), activities, config); const season = { ...rawSeason, score: rawSeason.points, stats: { yannick: publicStats(rawSeason.participants.yannick), emma: publicStats(rawSeason.participants.emma) }, participants: { yannick: publicStats(rawSeason.participants.yannick), emma: publicStats(rawSeason.participants.emma) } }; const history = Object.values(weeks).sort((a, b) => String(b.weekStart).localeCompare(String(a.weekStart))).map(w => ({ weekStart: w.weekStart, dateRange: w.dateRange, dateLabel: w.dateRange, score: { yannick: w.yannick?.qualifyingActivities || 0, emma: w.emma?.qualifyingActivities || 0 }, qualifyingTimeSeconds: { yannick: w.yannick?.qualifyingActivityTime || 0, emma: w.emma?.qualifyingActivityTime || 0 }, winner: w.winner, winningMethod: w.winningMethod, yannick: publicStats(w.yannick), emma: publicStats(w.emma), seasonScoreAfter: { yannick: Number(w.seasonScoreAfter?.yannick) || 0, emma: Number(w.seasonScoreAfter?.emma) || 0 }, finalized: true })); return { configured: true, challenge: { name: 'Strava Cup', year: rawSeason.year, timezone: CHALLENGE_TIME_ZONE }, participants: PARTICIPANTS, currentWeek: { ...currentWeek, activities: activities.filter(a => inBounds(a, bounds)).sort((a,b) => new Date(b.startDate) - new Date(a.startDate)).map(withCurrentEvaluation).map(publicActivity) }, season, history, lastUpdated: state.lastSuccessfulSync || null, lastUpdatedAt: state.lastSuccessfulSync || null, stale: false }; }
function buildPublicWeek(state = {}, weekStart) { const w = (state.weeks || state.finalizedWeeks || {})[weekStart]; if (!w) return null; const activities = w.activities || []; const yannick = publicStats(w.yannick), emma = publicStats(w.emma); return { weekStart: w.weekStart, dateRange: w.dateRange, dateLabel: w.dateRange, winner: w.winner, winningMethod: w.winningMethod, pointAwarded: w.pointAwarded, finalized: true, score: { yannick: yannick.qualifyingActivities || 0, emma: emma.qualifyingActivities || 0 }, qualifyingTimeSeconds: { yannick: yannick.qualifyingActivityTime || 0, emma: emma.qualifyingActivityTime || 0 }, stats: { yannick, emma }, yannick, emma, seasonScoreAfter: { yannick: Number(w.seasonScoreAfter?.yannick) || 0, emma: Number(w.seasonScoreAfter?.emma) || 0 }, activities: activities.map(publicActivity) }; }
module.exports = { PARTICIPANTS, THRESHOLDS, categorizeSportType, activityDurationSeconds, evaluateActivity, normalizeActivity, calculateParticipantStats, calculateWeekResult, calculateSeason, buildPublicDashboard, buildPublicWeek, _test: { prettyAmount, inBounds } };
