'use strict';

const path = require('path');
const { createStore, PARTICIPANTS } = require('./store');
const { encrypt, decrypt, randomToken, tokenHash, equalHash, ChallengeCryptoError } = require('./crypto');
const { createStravaClient, StravaClientError, requireScope } = require('./strava-client');
const { normalizeActivity, calculateWeekResult, calculateSeason, buildPublicDashboard, buildPublicWeek } = require('./domain');
const { getWeekBounds, getPreviousWeekBounds, getChallengeRange, isMondayFinalizationDue } = require('./time');
const { renderConnectionEmail, renderWeeklyEmails } = require('./emails');

class StravaChallengeError extends Error { constructor(message, code = 'challenge_error') { super(message); this.name = 'StravaChallengeError'; this.code = code; } }
const emailOk = value => typeof value === 'string' && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
const clone = value => JSON.parse(JSON.stringify(value));
function ensureParticipant(id) { if (!PARTICIPANTS[id]) throw new StravaChallengeError('Unknown challenge participant.', 'unknown_participant'); return id; }
function createStravaChallenge({ dataDir = path.join(process.cwd(), 'data', 'strava-challenge'), env = process.env, sendEmail = async () => ({ skipped: true }), fetchImpl = global.fetch, now = () => new Date(), logger = console } = {}) {
  const store = createStore({ dataDir, env, now }); const client = createStravaClient({ env, fetchImpl }); const sendingInvites = new Map(); const participantLocks = new Map(); let finalizeChain = Promise.resolve(); let interval = null, startup = null;
  const log = (method, message) => { try { if (logger && typeof logger[method] === 'function') logger[method](`[strava-challenge] ${message}`); } catch {} };
  function privateState() { return store.read(s => s); }
  function credentials(p) { if (!p || !p.connection) return null; return { accessToken: decrypt(p.connection.accessToken, `${p.id}:access`, env), refreshToken: decrypt(p.connection.refreshToken, `${p.id}:refresh`, env), expiresAt: +p.connection.expiresAt || 0 }; }
  function withParticipantLock(id, fn) { const prior = participantLocks.get(id) || Promise.resolve(); const run = prior.then(fn, fn); participantLocks.set(id, run.catch(() => {})); return run; }
  function inviteUrl(token) { const base = privateState().config.baseUrl || (env.CHALLENGE_BASE_URL || env.PUBLIC_BASE_URL || '').replace(/\/+$/, ''); if (!base) throw new StravaChallengeError('CHALLENGE_BASE_URL is required to send a connection invitation.', 'missing_base_url'); return `${base}/strava-connect/#token=${encodeURIComponent(token)}`; }
  async function generateInvite(participantId) { ensureParticipant(participantId); const raw = randomToken(), createdAt = now().toISOString(); await store.mutate(s => { const p = s.participants[participantId]; if (!p) throw new StravaChallengeError('Unknown participant.', 'unknown_participant'); for (const inv of Object.values(s.invites)) if (inv.participantId === participantId && !inv.usedAt && !inv.revokedAt) inv.revokedAt = createdAt; const id = randomToken(); s.invites[id] = { id, participantId, tokenHash: tokenHash(raw), createdAt, expiresAt: new Date(now().getTime() + s.config.inviteTtlHours * 3600000).toISOString(), usedAt: null, revokedAt: null, emailSentAt: null }; }); return { participantId, url: inviteUrl(raw), token: raw, expiresAt: new Date(now().getTime() + privateState().config.inviteTtlHours * 3600000).toISOString() }; }
  function findInvite(s, raw) { const found = Object.values(s.invites).find(inv => equalHash(raw, inv.tokenHash)); if (!found || found.usedAt || found.revokedAt || new Date(found.expiresAt).getTime() <= now().getTime()) throw new StravaChallengeError('This Strava connection link is invalid or expired.', 'invalid_invite'); return found; }
  async function sendInvite(participantId) { ensureParticipant(participantId); const p = privateState().participants[participantId]; if (!emailOk(p.email)) throw new StravaChallengeError('A valid private email address must be configured before sending an invite.', 'missing_email'); const created = await generateInvite(participantId); try { const message = renderConnectionEmail({ participantId, connectUrl: created.url, expiresAt: created.expiresAt }); const result = await sendEmail(p.email, { ...message, from: env.STRAVA_CHALLENGE_FROM_EMAIL || 'challenge@yannickmorgans.ca', idempotencyKey: `strava-invite-${participantId}-${tokenHash(created.token)}` }); await store.mutate(s => { const inv = Object.values(s.invites).find(x => equalHash(created.token, x.tokenHash)); if (inv) inv.emailSentAt = now().toISOString(); }); return { participantId, sent: !result || !result.skipped, result: result && result.skipped ? { skipped: true, reason: result.reason } : { ok: true } }; } finally { created.token = undefined; created.url = undefined; }
  }
  async function prepareOAuth(inviteToken) { if (!inviteToken || typeof inviteToken !== 'string') throw new StravaChallengeError('A connection invitation is required.', 'invalid_invite'); const state = randomToken(), createdAt = now().toISOString(); let participantId; await store.mutate(s => { const inv = findInvite(s, inviteToken); participantId = inv.participantId; const id = randomToken(); s.oauthStates[id] = { id, stateHash: tokenHash(state), inviteId: inv.id, participantId, createdAt, expiresAt: new Date(now().getTime() + 15 * 60 * 1000).toISOString(), usedAt: null, claimedAt: null }; }); return { participantId, authorizeUrl: client.authorizeUrl(state), expiresAt: new Date(now().getTime() + 15 * 60 * 1000).toISOString() }; }
  async function claimState(state) { let selected; await store.mutate(s => { selected = Object.values(s.oauthStates).find(x => equalHash(state, x.stateHash)); if (!selected || selected.usedAt || selected.claimedAt || new Date(selected.expiresAt).getTime() <= now().getTime()) throw new StravaChallengeError('This Strava authorization session is invalid or expired.', 'invalid_oauth_state'); const invite = s.invites[selected.inviteId]; if (!invite || invite.usedAt || invite.revokedAt || new Date(invite.expiresAt).getTime() <= now().getTime()) throw new StravaChallengeError('This Strava connection invitation is no longer valid.', 'invalid_invite'); selected.claimedAt = now().toISOString(); }); return selected; }
  async function releaseState(id) { await store.mutate(s => { if (s.oauthStates[id] && !s.oauthStates[id].usedAt) s.oauthStates[id].claimedAt = null; }); }
  async function completeOAuth({ code, state, scope, error } = {}) { if (error) throw new StravaChallengeError('Strava authorization was not completed.', 'oauth_denied'); if (!code || !state) throw new StravaChallengeError('Missing Strava authorization response.', 'invalid_oauth_callback'); if (scope) requireScope(scope); const oauth = await claimState(state); let token; try { token = await client.exchangeCode(code); requireScope(token.scope || scope); } catch (e) { await releaseState(oauth.id); throw e; } const athleteId = String(token.athlete && token.athlete.id || ''); if (!athleteId) { await releaseState(oauth.id); throw new StravaChallengeError('Strava did not return an athlete identity.', 'invalid_athlete'); }
    try { await store.mutate(s => { const current = s.oauthStates[oauth.id], invite = s.invites[oauth.inviteId]; if (!current || !current.claimedAt || current.usedAt || !invite || invite.usedAt) throw new StravaChallengeError('This authorization session has already been used.', 'invalid_oauth_state'); for (const other of Object.values(s.participants)) if (other.id !== oauth.participantId && String(other.connection && other.connection.athleteId || '') === athleteId) throw new StravaChallengeError('That Strava athlete is already connected to the other participant.', 'athlete_already_connected'); const p = s.participants[oauth.participantId]; p.connection = { athleteId, athlete: { id: athleteId, firstname: String(token.athlete.firstname || ''), lastname: String(token.athlete.lastname || '') }, accessToken: encrypt(token.access_token, `${p.id}:access`, env), refreshToken: encrypt(token.refresh_token, `${p.id}:refresh`, env), expiresAt: Number(token.expires_at) * 1000, scopes: String(token.scope || scope || 'activity:read_all') }; p.connected = true; p.lastSyncAt = null; invite.usedAt = now().toISOString(); current.usedAt = now().toISOString(); current.claimedAt = null; }); } catch (e) { await releaseState(oauth.id); throw e; }
    let sync; try { sync = await syncParticipant(oauth.participantId, { initial: true }); } catch (e) { log('warn', `Initial activity sync failed for ${oauth.participantId}: ${e.message}`); sync = { ok: false, error: 'Initial sync will retry automatically.' }; } return { participantId: oauth.participantId, connected: true, sync };
  }
  async function accessFor(id) { const p = privateState().participants[id]; if (!p || !p.connected || !p.connection) throw new StravaChallengeError('This participant has not connected Strava.', 'not_connected'); let creds = credentials(p); if (creds.expiresAt <= now().getTime() + 3600000) { const refreshed = await client.refresh(creds.refreshToken); await store.mutate(s => { const target = s.participants[id]; if (!target.connection) throw new StravaChallengeError('Strava connection changed while refreshing.', 'connection_changed'); target.connection.accessToken = encrypt(refreshed.access_token, `${id}:access`, env); target.connection.refreshToken = encrypt(refreshed.refresh_token, `${id}:refresh`, env); target.connection.expiresAt = Number(refreshed.expires_at) * 1000; target.connection.scopes = String(refreshed.scope || target.connection.scopes); }); creds = { accessToken: refreshed.access_token, refreshToken: refreshed.refresh_token, expiresAt: Number(refreshed.expires_at) * 1000 }; } return creds;
  }
  async function syncParticipant(id, options = {}) { ensureParticipant(id); return withParticipantLock(id, async () => { const beforeState = privateState(), p = beforeState.participants[id]; if (!p.connected) throw new StravaChallengeError('This participant has not connected Strava.', 'not_connected'); let bounds; if (options.bounds) bounds = options.bounds; else if (options.initial || !p.initialSync || !p.initialSync.complete) { const range = getChallengeRange(beforeState.config, now()); bounds = { start: new Date(beforeState.config.challengeStart || range.start), end: range.end, weekStart: null }; } else { const current = getWeekBounds(now()); const prior = getPreviousWeekBounds(now()); bounds = { start: prior.start, end: current.end, weekStart: null }; }
      const creds = await accessFor(id); const response = await client.listActivities(creds.accessToken, bounds); const received = new Set(response.activities.map(a => String(a.id))); const syncedAt = now().toISOString(); await store.mutate(s => { for (const raw of response.activities) { const a = normalizeActivity(raw, id, syncedAt); if (a.externalId) s.activities[a.externalId] = { ...(s.activities[a.externalId] || {}), ...a, deletedAt: null }; } for (const [key, a] of Object.entries(s.activities)) if (a.participantId === id && new Date(a.startDate).getTime() >= new Date(bounds.start).getTime() && new Date(a.startDate).getTime() < new Date(bounds.end).getTime() && !received.has(String(a.externalId || key))) a.deletedAt = syncedAt; const target = s.participants[id]; target.lastSyncAt = syncedAt; target.lastSyncError = null; if (options.initial || !target.initialSync) target.initialSync = { complete: true, startedAt: target.initialSync && target.initialSync.startedAt || syncedAt, completedAt: syncedAt, rangeStart: new Date(bounds.start).toISOString(), rangeEnd: new Date(bounds.end).toISOString() }; s.lastSuccessfulSync = syncedAt; }); return { ok: true, participantId: id, count: response.activities.length, range: { start: new Date(bounds.start).toISOString(), end: new Date(bounds.end).toISOString() }, rateLimit: response.rateLimit }; }); }
  async function syncAll(options = {}) { const results = await Promise.allSettled(Object.keys(PARTICIPANTS).map(id => syncParticipant(id, options))); return Object.fromEntries(Object.keys(PARTICIPANTS).map((id, index) => [id, results[index].status === 'fulfilled' ? results[index].value : { ok: false, error: results[index].reason.message }])); }
  function activeActivities(s) { return Object.values(s.activities).filter(a => !a.deletedAt); }
  function previewFinalization(weekStart) { const s = privateState(); const bounds = weekStart ? getWeekBounds(new Date(`${weekStart}T12:00:00Z`)) : getPreviousWeekBounds(now()); if (weekStart && bounds.weekStart !== weekStart) throw new StravaChallengeError('Invalid week start.', 'invalid_week'); return calculateWeekResult(activeActivities(s), bounds); }
  async function finalizeWeek({ weekStart, confirm, manual = false } = {}) { const begin = async () => { const bounds = weekStart ? getWeekBounds(new Date(`${weekStart}T12:00:00Z`)) : getPreviousWeekBounds(now()); if (!/\d{4}-\d{2}-\d{2}/.test(bounds.weekStart)) throw new StravaChallengeError('Invalid week.', 'invalid_week'); if (manual && confirm !== `FINALIZE ${bounds.weekStart}`) throw new StravaChallengeError(`Confirmation must be exactly FINALIZE ${bounds.weekStart}.`, 'confirmation_required'); const existing = privateState().weeks[bounds.weekStart] || privateState().finalizedWeeks && privateState().finalizedWeeks[bounds.weekStart]; if (existing) return { ...clone(existing), alreadyFinalized: true };
      const results = await Promise.allSettled(Object.keys(PARTICIPANTS).map(id => syncParticipant(id, { bounds }))); if (results.some(r => r.status !== 'fulfilled')) throw new StravaChallengeError('Unable to finalize: Strava sync did not succeed for both participants.', 'sync_failed'); let snapshot; await store.mutate(s => { s.weeks ||= {}; s.finalizedWeeks ||= s.weeks; if (s.weeks[bounds.weekStart]) { snapshot = clone(s.weeks[bounds.weekStart]); return; } const result = calculateWeekResult(activeActivities(s), bounds); const frozenActivities = activeActivities(s).filter(a => { const t = new Date(a.startDate).getTime(); return t >= bounds.start.getTime() && t < bounds.end.getTime(); }).map(clone); const provisional = { ...result, finalized: true, finalizedAt: now().toISOString(), activities: frozenActivities, email: {} }; const all = [...Object.values(s.weeks), provisional]; const season = calculateSeason(all, activeActivities(s), s.config); provisional.seasonScoreAfter = season.points; s.weeks[bounds.weekStart] = provisional; s.finalizedWeeks = s.weeks; snapshot = clone(provisional); }); await deliverResultEmails(snapshot); return snapshot; };
    const run = finalizeChain.then(begin, begin); finalizeChain = run.catch(() => {}); return run;
  }
  async function deliverResultEmails(snapshot) { const currentState = privateState(); const base = String(currentState.config.baseUrl || env.CHALLENGE_BASE_URL || env.PUBLIC_BASE_URL || '').replace(/\/+$/, ''); const messages = renderWeeklyEmails(snapshot, { weekUrl: base ? `${base}/?week=${encodeURIComponent(snapshot.weekStart)}#strava-challenge` : '' }); for (const id of Object.keys(PARTICIPANTS)) { const s = privateState(), current = s.weeks[snapshot.weekStart]; if (!current || current.email && current.email[id] && current.email[id].status) continue; const p = s.participants[id]; if (!emailOk(p.email)) continue; await store.mutate(state => { const w = state.weeks[snapshot.weekStart]; w.email ||= {}; if (!w.email[id]) w.email[id] = { status: 'sending', startedAt: now().toISOString() }; }); try { await sendEmail(p.email, { ...messages[id], from: env.STRAVA_CHALLENGE_FROM_EMAIL || 'challenge@yannickmorgans.ca', idempotencyKey: `strava-result-${snapshot.weekStart}-${id}` }); await store.mutate(state => { state.weeks[snapshot.weekStart].email[id] = { status: 'sent', sentAt: now().toISOString() }; }); } catch (e) { log('warn', `Result email failed for ${id}: ${e.message}`); /* retain sending state so retries cannot duplicate ambiguous delivery */ } }
  }
  function getAdminStatus() { return store.read(s => ({ config: clone(s.config), participants: Object.values(s.participants).map(p => ({ id: p.id, name: p.name, color: p.color, email: p.email, connected: p.connected, stravaAthleteId: p.connection && p.connection.athleteId || null, lastSyncAt: p.lastSyncAt, lastSyncError: p.lastSyncError || null, initialSync: p.initialSync || null, invite: Object.values(s.invites).filter(i => i.participantId === p.id).sort((a,b) => String(b.createdAt).localeCompare(String(a.createdAt)))[0] && (({ createdAt, expiresAt, usedAt, revokedAt, emailSentAt }) => ({ createdAt, expiresAt, usedAt, revokedAt, emailSentAt }))(Object.values(s.invites).filter(i => i.participantId === p.id).sort((a,b) => String(b.createdAt).localeCompare(String(a.createdAt)))[0]) })) })); }
  async function updateConfig(input = {}) { const allowed = ['challengeYear', 'challengeStart', 'baseUrl', 'inviteTtlHours', 'syncIntervalMinutes', 'finalizeHour']; const emails = { yannick: input.yannickEmail, emma: input.emmaEmail }; await store.mutate(s => { for (const key of allowed) if (Object.prototype.hasOwnProperty.call(input, key)) s.config[key] = input[key]; if (!Number.isInteger(+s.config.challengeYear) || +s.config.challengeYear < 2020 || +s.config.challengeYear > 2100) throw new StravaChallengeError('Challenge year must be valid.', 'invalid_config'); if (!/^\d{4}-\d{2}-\d{2}$/.test(String(s.config.challengeStart))) throw new StravaChallengeError('Challenge start must be YYYY-MM-DD.', 'invalid_config'); if (!Number.isFinite(+s.config.syncIntervalMinutes) || +s.config.syncIntervalMinutes < 5 || +s.config.syncIntervalMinutes > 1440) throw new StravaChallengeError('Sync interval must be 5–1440 minutes.', 'invalid_config'); if (!Number.isInteger(+s.config.finalizeHour) || +s.config.finalizeHour < 0 || +s.config.finalizeHour > 23) throw new StravaChallengeError('Finalization hour must be 0–23.', 'invalid_config'); for (const id of Object.keys(emails)) if (emails[id] !== undefined) { if (emails[id] !== '' && !emailOk(emails[id])) throw new StravaChallengeError('Email address is invalid.', 'invalid_config'); s.participants[id].email = emails[id] || null; } }); return getAdminStatus(); }
  function previewEmail({ type, participantId } = {}) { ensureParticipant(participantId); const state = privateState(); const to = state.participants[participantId].email ? 'configured recipient' : 'no recipient configured'; if (type === 'invite' || type === 'connection') return { to, ...renderConnectionEmail({ participantId, connectUrl: `${String(state.config.baseUrl || 'https://example.invalid').replace(/\/+$/, '')}/strava-connect/#token=preview-token`, expiresAt: new Date(now().getTime() + 86400000).toISOString() }) }; const week = previewFinalization(); const seasonScoreAfter = calculateSeason(Object.values(state.weeks || {}), activeActivities(state), state.config).points; return { to, week, ...renderWeeklyEmails({ ...week, seasonScoreAfter }, { weekUrl: state.config.baseUrl ? `${state.config.baseUrl}/?week=${encodeURIComponent(week.weekStart)}#strava-challenge` : '' })[participantId] }; }
  async function resetForSeasonStart({ confirm } = {}) { if (confirm !== 'RESET STRAVA CHALLENGE') throw new StravaChallengeError('Confirmation must be exactly RESET STRAVA CHALLENGE.', 'confirmation_required'); await store.mutate(s => { s.activities = {}; s.weeks = {}; s.finalizedWeeks = s.weeks; s.lastSuccessfulSync = null; s.emailState = {}; s.scheduler = { lastRunAt: null }; for (const p of Object.values(s.participants)) { p.lastSyncAt = null; p.lastSyncError = null; p.initialSync = null; } }); return { ok: true, resetAt: now().toISOString() }; }
  function schedulerTick() { return Promise.resolve().then(async () => { const s = privateState(); if (isMondayFinalizationDue(now(), +s.config.finalizeHour)) await finalizeWeek({ manual: false }); await syncAll(); await store.mutate(state => { state.scheduler.lastRunAt = now().toISOString(); }); }).catch(e => log('warn', `Scheduled Strava work failed: ${e.message}`)); }
  function startScheduler() { if (interval) return; const ms = Math.max(5, +privateState().config.syncIntervalMinutes || 15) * 60000; startup = setTimeout(schedulerTick, 30000); interval = setInterval(schedulerTick, ms); }
  function stopScheduler() { if (interval) clearInterval(interval); if (startup) clearTimeout(startup); interval = startup = null; }
  return { getPublicDashboard: async () => store.read(s => buildPublicDashboard({ ...s, activities: Object.fromEntries(activeActivities(s).map(a => [a.externalId || a.id, a])), finalizedWeeks: s.weeks || s.finalizedWeeks }, now())), getPublicWeek: async weekStart => store.read(s => buildPublicWeek({ ...s, finalizedWeeks: s.weeks || s.finalizedWeeks }, weekStart)), getAdminStatus: async () => getAdminStatus(), updateConfig, generateInvite, sendInvite, prepareOAuth, completeOAuth, syncParticipant, syncAll, previewFinalization: async week => previewFinalization(week), finalizeWeek, previewEmail: async input => previewEmail(input), resetForSeasonStart, startScheduler, stopScheduler, _test: { store, credentials, activeActivities } };
}
module.exports = { createStravaChallenge, StravaChallengeError, StravaClientError, ChallengeCryptoError };
