'use strict';

class StravaClientError extends Error { constructor(message, { status, retryAfter, code } = {}) { super(message); this.name = 'StravaClientError'; this.status = status; this.retryAfter = retryAfter; this.code = code; } }
const BASE = 'https://www.strava.com'; const API = 'https://www.strava.com/api/v3';
function scopes(value) { return new Set(String(value || '').split(/[ ,]+/).filter(Boolean)); }
function requireScope(value) { if (!scopes(value).has('activity:read_all')) throw new StravaClientError('Strava did not grant activity:read_all. Please reconnect and approve activity access.', { code: 'missing_scope' }); }
function createStravaClient({ env = process.env, fetchImpl = global.fetch, timeoutMs = 15000 } = {}) {
  if (typeof fetchImpl !== 'function') throw new StravaClientError('Fetch is unavailable for Strava requests.');
  const clientId = env.STRAVA_CLIENT_ID, clientSecret = env.STRAVA_CLIENT_SECRET, redirectUri = env.STRAVA_REDIRECT_URI;
  function configured() { if (!clientId || !clientSecret || !redirectUri) throw new StravaClientError('Strava OAuth is not configured.', { code: 'unconfigured' }); }
  async function request(url, options = {}) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); try { const response = await fetchImpl(url, { ...options, signal: controller.signal }); const text = await response.text(); let body; try { body = text ? JSON.parse(text) : {}; } catch { body = {}; } if (!response.ok) { const retryAfter = Number(response.headers && response.headers.get('retry-after')) || null; throw new StravaClientError(response.status === 429 ? 'Strava rate limit reached.' : `Strava request failed (${response.status}).`, { status: response.status, retryAfter, code: body.message }); } return { body, headers: response.headers }; } catch (error) { if (error instanceof StravaClientError) throw error; throw new StravaClientError(error && error.name === 'AbortError' ? 'Strava request timed out.' : 'Strava network request failed.', { code: 'network' }); } finally { clearTimeout(timer); } }
  function authorizeUrl(state) { configured(); const q = new URLSearchParams({ client_id: clientId, redirect_uri: redirectUri, response_type: 'code', approval_prompt: 'force', scope: 'activity:read_all', state }); return `${BASE}/oauth/authorize?${q}`; }
  async function token(body) { configured(); const result = await request(`${BASE}/oauth/token`, { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ client_id: clientId, client_secret: clientSecret, ...body }).toString() }); return result.body; }
  async function exchangeCode(code) { return token({ code, grant_type: 'authorization_code' }); }
  async function refresh(refreshToken) { return token({ refresh_token: refreshToken, grant_type: 'refresh_token' }); }
  async function listActivities(accessToken, { after, before } = {}) { const all = []; for (let page = 1; page < 1000; page++) { const q = new URLSearchParams({ per_page: '100', page: String(page) }); if (after != null) q.set('after', String(Math.floor(new Date(after).getTime() / 1000) - 1)); if (before != null) q.set('before', String(Math.floor(new Date(before).getTime() / 1000))); const { body, headers } = await request(`${API}/athlete/activities?${q}`, { headers: { Authorization: `Bearer ${accessToken}` } }); if (!Array.isArray(body)) throw new StravaClientError('Unexpected Strava activity response.'); all.push(...body); if (body.length < 100) return { activities: all, rateLimit: headers && headers.get('x-ratelimit-usage'), rateLimitLimit: headers && headers.get('x-ratelimit-limit') }; } throw new StravaClientError('Strava activity pagination exceeded the safety limit.'); }
  return { authorizeUrl, exchangeCode, refresh, listActivities, requireScope };
}
module.exports = { createStravaClient, StravaClientError, requireScope };
